### ISSUE TITLE
Error when beginning password recovery process

### ISSUE THREAD

**Issue by jliedy** [jrivard/pwm#10]
After upgrading from the 2014 February release to pwm-20150907-0600.war, this is the message I am getting when starting the password recovery process.

Stacktrace added:
2015-09-07T13:00:05Z, ERROR, http.PwmRequest, {0} 5015 ERROR_UNKNOWN (unexpected error processing request: Unable to compile class for JSP:  [98.230.0.226]

An error occurred at line: 35 in the jsp file: /WEB-INF/jsp/fragment/forgottenpassword-cancel.jsp
PwmServletDefinition.ForgottenPassword cannot be resolved to a type
32:         <script type="text/javascript">
33:             PWM_GLOBAL['startupFunctions'].push(function(){
34:                 PWM_MAIN.addEventHandler('button-sendReset', 'click',function() {
35:                     PWM_MAIN.submitPostAction('<%=PwmServletDefinition.ForgottenPassword.servletUrlName()%>', '<%=ForgottenPasswordServlet.ForgottenPasswordAction.reset%>');
36:                 });
37:             });
38:         </script>

Stacktrace:
org.apache.jasper.JasperException: Unable to compile class for JSP:

An error occurred at line: 35 in the jsp file: /WEB-INF/jsp/fragment/forgottenpassword-cancel.jsp
PwmServletDefinition.ForgottenPassword cannot be resolved to a type
32:         <script type="text/javascript">
33:             PWM_GLOBAL['startupFunctions'].push(function(){
34:                 PWM_MAIN.addEventHandler('button-sendReset', 'click',function() {
35:                     PWM_MAIN.submitPostAction('<%=PwmServletDefinition.ForgottenPassword.servletUrlName()%>', '<%=ForgottenPasswordServlet.ForgottenPasswordAction.reset%>');
36:                 });
37:             });
38:         </script>

Stacktrace:
        at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
        at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:366)
        at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:485)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:379)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:354)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:341)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:662)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:364)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:395)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:339)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:748)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:486)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:411)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:338)
        at password.pwm.http.PwmResponse.forwardToJsp(PwmResponse.java:70)
        at password.pwm.http.PwmRequest.forwardToJsp(PwmRequest.java:154)
        at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processVerificationChoice(ForgottenPasswordServlet.java:315)
        at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.advancedToNextStage(ForgottenPasswordServlet.java:731)
        at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processAction(ForgottenPasswordServlet.java:235)
        at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:108)
        at password.pwm.http.servlet.AbstractPwmServlet.doPost(AbstractPwmServlet.java:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:650)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:100)
        at password.pwm.http.filter.CaptchaFilter.processFilter(CaptchaFilter.java:53)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:100)
        at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:83)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:100)
        at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:70)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:94)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at password.pwm.http.filter.ApplicationStatusFilter.doFilter(ApplicationStatusFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:505)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:170)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
        at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:957)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:423)
        at org.apache.coyote.ajp.AjpProcessor.process(AjpProcessor.java:190)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:620)
        at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
)

**Comment by jliedy** [comment]
And now it's not doing it anymore.  I worked around in the config and couldn't tell you which change I made that caused it to work correctly.

**Comment by drfarnsworth** [comment]
I still have this problem with pwm-20150922-0600.war

My Forgotten Password Configuration is: 

Modules -> Forgotten Password -> Forgotten Password Profiles -> default
Verification Methods
Challenge/REsponse Answers : Optional
SMS/Email Token Verifikation : Optional
Rest : Not Used
Minium Optional Requirements : 1
Tokens Send Method : Email Only - Send to email address


Here the Stacktrace: 
An error occurred at line: 35 in the jsp file: /WEB-INF/jsp/fragment/forgottenpassword-cancel.jsp
PwmServletDefinition.ForgottenPassword cannot be resolved to a type
32:         <script type="text/javascript">
33:             PWM_GLOBAL['startupFunctions'].push(function(){
34:                 PWM_MAIN.addEventHandler('button-sendReset', 'click',function() {
35:                     PWM_MAIN.submitPostAction('<%=PwmServletDefinition.ForgottenPassword.servletUrlName()%>', '<%=ForgottenPasswordServlet.ForgottenPasswordAction.reset%>');
36:                 });
37:             });
38:         </script>


Stacktrace:
        at org.apache.jasper.compiler.DefaultErrorHandler.javacError(DefaultErrorHandler.java:103)
        at org.apache.jasper.compiler.ErrorDispatcher.javacError(ErrorDispatcher.java:199)
        at org.apache.jasper.compiler.JDTCompiler.generateClass(JDTCompiler.java:446)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:361)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:336)
        at org.apache.jasper.compiler.Compiler.compile(Compiler.java:323)
        at org.apache.jasper.JspCompilationContext.compile(JspCompilationContext.java:564)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:357)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:405)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:349)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:721)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:466)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:391)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:318)
        at password.pwm.http.PwmResponse.forwardToJsp(PwmResponse.java:71)
        at password.pwm.http.PwmRequest.forwardToJsp(PwmRequest.java:151)
        at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processVerificationChoice(ForgottenPasswordServlet.java:316)
        at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.advancedToNextStage(ForgottenPasswordServlet.java:732)
        at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processAction(ForgottenPasswordServlet.java:236)
        at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:108)
        at password.pwm.http.servlet.AbstractPwmServlet.doPost(AbstractPwmServlet.java:64)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:644)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:725)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:100)
        at password.pwm.http.filter.CaptchaFilter.processFilter(CaptchaFilter.java:53)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:100)
        at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:82)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:100)
        at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:70)
        at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:62)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:94)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:68)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at password.pwm.http.filter.ApplicationStatusFilter.doFilter(ApplicationStatusFilter.java:32)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:503)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:136)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:610)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:526)
        at org.apache.coyote.ajp.AbstractAjpProcessor.process(AbstractAjpProcessor.java:823)
        at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:655)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1566)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1523)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)
)

**Comment by zuglufttier** [comment]
I have the same problem, too!

This seems to happen when you choose more than one verification method. I want to configure two verification methods and make both optional so the user can choose one of the two or none at all.
If I choose only one verification method everything is working nicely.

**Comment by zuglufttier** [comment]
Fixed here: https://www.google.com/url?q=https%3A%2F%2Fgithub.com%2Fjrivard%2Fpwm%2Fcommit%2Fde0bea75362368aca0abe601a21e35035b5e2009&sa=D&sntz=1&usg=AFQjCNGIstzpb0-Vj42A4u6TmoKz3_z0xg
