### ISSUE TITLE
OTP recovery codes don't work

### ISSUE THREAD

**Issue by zuglufttier** [jrivard/pwm#17]

**Comment by zuglufttier** [comment]
I tried using LocalDB as storage which also did not work, this is from the logs:

````
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: 2015-09-29T15:41:06Z, INFO , forgottenpw.ForgottenPasswordServlet, {k} checking entered OTP [139.13.238.61]
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: 2015-09-29T15:41:06Z, FATAL, servlet.AbstractPwmServlet, 5015 ERROR_UNKNOWN (unexpected error processing request: null
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: java.lang.NullPointerException
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.util.operations.OtpService.writeOTPUserConfiguration(OtpService.java:303)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.util.operations.OtpService.validateToken(OtpService.java:123)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processEnterOtpToken(ForgottenPasswordServlet.java:529)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.servlet.forgottenpw.ForgottenPasswordServlet.processAction(ForgottenPasswordServlet.java:203)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.servlet.AbstractPwmServlet.handleRequest(AbstractPwmServlet.java:108)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.servlet.AbstractPwmServlet.doPost(AbstractPwmServlet.java:64)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:303)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:100)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.CaptchaFilter.processFilter(CaptchaFilter.java:53)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:62)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:100)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.SessionFilter.processFilter(SessionFilter.java:82)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:62)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.AbstractPwmFilter$PwmFilterChain.doFilter(AbstractPwmFilter.java:100)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.ApplicationModeFilter.processFilter(ApplicationModeFilter.java:70)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.AbstractPwmFilter.doFilter(AbstractPwmFilter.java:62)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.RequestInitializationFilter.doFilter(RequestInitializationFilter.java:94)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.GZIPFilter.doFilter(GZIPFilter.java:68)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at password.pwm.http.filter.ApplicationStatusFilter.doFilter(ApplicationStatusFilter.java:32)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:241)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:208)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:220)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:122)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:501)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:950)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:116)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1040)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:607)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:316)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: at java.lang.Thread.run(Thread.java:745)
Sep 29 15:41:06 xxx.xxxxx.xx server[3296]: )
```

**Comment by zuglufttier** [comment]
Sorry, I overlooked something...

**Comment by jrivard** [comment]
most common cause is server time isn't correct.
