### ISSUE TITLE
NoSuchMethodError   password.pwm.http.filter.ApplicationStatusFilter.doFilter

### ISSUE THREAD

**Issue by edperry** [jrivard/pwm#18]
Tried deploying both pwm-LATEST and pwm-20150913-0600.war

Both I did as directed and I have the latest java-1.7 installed and Tomcat6  Both provided from REDHAT RPMS

tomcat6-servlet-2.5-api-6.0.24-90.el6.x86_64
tomcat6-6.0.24-90.el6.x86_64
java-1.7.0-openjdk-1.7.0.85-2.6.1.3.el6_7.x86_64

#Message in the browser
```
HTTP Status 500 - type Exception report  message
description The server encountered an internal error () that prevented it from fulfilling this request.

exception
javax.servlet.ServletException: Filter execution threw an exception

root cause
java.lang.NoSuchMethodError: javax.servlet.ServletRequest.getServletContext()Ljavax/servlet/ServletContext;
	password.pwm.http.filter.ApplicationStatusFilter.doFilter(ApplicationStatusFilter.java:25)
note The full stack trace of the root cause is available in the Apache Tomcat/6.0.24 logs.
```

#From the logs
This is what I see in the logs
```
Sep 29, 2015 4:43:34 PM org.apache.catalina.core.StandardHostValve custom
SEVERE: Exception Processing ErrorPage[errorCode=500, location=/WEB-INF/jsp/error-http.jsp]
org.apache.jasper.JasperException: An exception occurred processing JSP page /WEB-INF/jsp/error-http.jsp at line 66

63:         <br/>
64:         <br/>
65:         <div class="buttonbar">
66:             <form action="<pwm:url url='<%=PwmServletDefinition.Command.servletUrl()%>' addContext="true"/>" method="post" enctype="application/x-www-form-urlencoded">
67:                 <input type="hidden"
68:                        name="processAction"
69:                        value="continue"/>


Stacktrace:
        at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:510)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:401)
        at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:313)
        at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:260)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
        at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:646)
        at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:438)
        at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:374)
        at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:302)
        at org.apache.catalina.core.StandardHostValve.custom(StandardHostValve.java:415)
        at org.apache.catalina.core.StandardHostValve.status(StandardHostValve.java:342)
        at org.apache.catalina.core.StandardHostValve.throwable(StandardHostValve.java:286)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:141)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:298)
        at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:857)
        at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:588)
        at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:489)
        at java.lang.Thread.run(Thread.java:745)
Caused by: javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class password.pwm.http.servlet.PwmServletDefinition
        at org.apache.jasper.runtime.PageContextImpl.doHandlePageException(PageContextImpl.java:862)
        at org.apache.jasper.runtime.PageContextImpl.handlePageException(PageContextImpl.java:791)
        at org.apache.jsp.WEB_002dINF.jsp.error_002dhttp_jsp._jspService(error_002dhttp_jsp.java:393)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
        at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:377)
        ... 20 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class password.pwm.http.servlet.PwmServletDefinition
        at org.apache.jsp.WEB_002dINF.jsp.error_002dhttp_jsp._jspService(error_002dhttp_jsp.java:266)
        ... 23 more
```

**Comment by jrivard** [comment]
tomcat 7 or greater is required.
